[package]
name = "logger"
version = "0.1.0"
edition = "2021"
authors = ["hectorlobato"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
